default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: oleg-gorbunov_development

test:
  <<: *default
  database: oleg-gorbunov_test

production:
  <<: *default
  database: oleg-gorbunov_production
  username: oleg-gorbunov
  password: <%= ENV['OLEG-GORBUNOV_DATABASE_PASSWORD'] %>
